{"name": "test_search[xiaomi]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/imgs/_2020_06_17 01_26_04.png'", "trace": "self = <test_search.TestSearch object at 0x0000029FD53F4D88>, name = 'xiaomi'\n\n    @allure.story(\"搜索股票\")\n    @pytest.mark.yes\n    @pytest.mark.parametrize(\"name\", [\"alibaba\", \"xiaomi\"])\n    def test_search(self, name):\n        try:\n            self._search.search(name)\n            # self._search.add()\n            if self._search.is_choozen():\n                self._search.reset()\n                self._search.add()\n            hamcrest.assert_that(self._search.is_choozen(), hamcrest.equal_to(True))\n>           assert 0\nE           AssertionError: assert 0\n\nscripts\\test_search.py:36: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_search.TestSearch object at 0x0000029FD53F4D88>, name = 'xiaomi'\n\n    @allure.story(\"搜索股票\")\n    @pytest.mark.yes\n    @pytest.mark.parametrize(\"name\", [\"alibaba\", \"xiaomi\"])\n    def test_search(self, name):\n        try:\n            self._search.search(name)\n            # self._search.add()\n            if self._search.is_choozen():\n                self._search.reset()\n                self._search.add()\n            hamcrest.assert_that(self._search.is_choozen(), hamcrest.equal_to(True))\n            assert 0\n        except Exception as e:\n>           self.app.save_screen_shoot(\"\")\n\nscripts\\test_search.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.app.App object at 0x0000029FD5346148>, name = ''\n\n    def save_screen_shoot(self, name):\n        ''' 截图 名字已包含时间戳\n        :param name:\n        :return:\n        '''\n        filename=\"/imgs/{0}{1}.png\".format(name, time.strftime(\"_%Y_%m_%d %H_%M_%S\"))\n        self._driver.save_screenshot(filename)\n>       with open(filename,\"rb\") as content:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/imgs/_2020_06_17 01_26_04.png'\n\nbase\\basePage.py:34: FileNotFoundError"}, "attachments": [{"name": "log", "source": "de29db50-53ed-4441-bb9c-559eb78bf93d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "name", "value": "'xiaomi'"}], "start": 1592328357243, "stop": 1592328365262, "uuid": "2a3fc1aa-62b4-4a0d-9c51-acf345a40665", "historyId": "f723adc96479752718b64ebf45f4ebc1", "testCaseId": "4b48e6925072f81fa93dfa41e68a9855", "fullName": "scripts.test_search.TestSearch#test_search", "labels": [{"name": "feature", "value": "雪球搜索功能"}, {"name": "story", "value": "搜索股票"}, {"name": "tag", "value": "yes"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_search"}, {"name": "subSuite", "value": "TestSearch"}, {"name": "host", "value": "LAPTOP-GVIPSB4C"}, {"name": "thread", "value": "20328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_search"}]}